### ISSUE TITLE
Public chat overlay default message after switching back from private chat

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#12130]
**Describe the bug**
When returning to public chat after reading/writing private conversation, the public chat is rendered false.

**To Reproduce**
1. at least 2 persons start meeting
2. one person writes the other in private chat
3. returning to public chat

**Expected behavior**
Switching between chats should have no rendering issues

**Screenshots**
![chat-overlay-bug](https://user-images.githubusercontent.com/856110/115886366-23829a00-a451-11eb-9074-5f3f7d81f37c.jpg)

**BBB version (optional):**
BBB 2.3 latest

**Desktop (please complete the following information):**
independent, screen resolution 1920x1080

**Comment by ramonlsouza** [comment]
this was fixed as part of PR #12102

**Comment by antobinary** [comment]
Should be shipped in next BBB release

**Comment by lonesomewalker** [comment]
Unfortunately not fixed.

It would be VERY NICE if issues are closed when the initial reporter says: closed.
Or if he is not responding after X days...

**Comment by PhMemmel** [comment]
Cannot reproduce with the steps provided in this issue, neither on own 2.3-rc1 installation nor on test23.bigbluebutton.org.
Are there any other things to consider when trying to reproduce this than the ones mentioned?

**Comment by lonesomewalker** [comment]
The thing is: me neither.
But we get constantly send emails with screenshots where the chat is still broken.

So, i guess users don't lie?

**Comment by ffdixon** [comment]
Want to make sure we've fixed this.  @lonesomewalker are you still getting reports of this on 2.3-rc-1?

**Comment by KDSBrowne** [comment]
@ffdixon I don't think this issue has  been fully fixed. There is still a problem with message clipping.
![default_msg_clipping](https://user-images.githubusercontent.com/22058534/116168506-8d5ca700-a6d0-11eb-8461-fd3bb55adfc0.gif)

**Comment by ramonlsouza** [comment]
I just made a new PR (#12170) to handle multiple private/public chat switching.

@lonesomewalker and @KDSBrowne could you please try it and check if this issue is still reproducible with the new changes?

**Comment by KDSBrowne** [comment]
I tested #12170. The solution worked to fix the clipping of the system message. It did however introduce a side effect that i just noticed. The public chat doesn't retain it's position and resets the chat scroll position based on where the system message is.
