### ISSUE TITLE
Changing the preferred locale from API is not working in 2.4

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#12687]
I passed `userdata-bbb_override_default_locale=de` in my custom parameters (in API mate and so on) and nothing happened in joining of the BBB session...

**To Reproduce**
1. API mate
2. Write `userdata-bbb_override_default_locale=de` in your custom parameter field (without any space)
3. click on joining attendee or ...
4. You can see that the `en` language is again enabled

**Comment by cod3r0k** [comment]
Hi @antobinary , Do you accept this issue?

**Comment by pedrobmarin** [comment]
I confirmed this issue a couple of weeks ago https://github.com/bigbluebutton/greenlight/issues/2636

**Comment by cod3r0k** [comment]
Dear @antobinary , do we have any schedule to handle this issue? If you need any help, please let me know.

**Comment by antobinary** [comment]
@cod3r0k absolutely, if you would take a look into this - by any means!
The schedule is to have this addressed in July/Aug 2021 (during the beta/rc phase of 2.4.x).

Would you like to give this issue a try?

**Comment by cod3r0k** [comment]
> @cod3r0k absolutely, if you would take a look into this - by any means!
> The schedule is to have this addressed in July/Aug 2021 (during the beta/rc phase of 2.4.x).
> 
> Would you like to give this issue a try?

Dear @antobinary , I tried to solve it but it isn't fixed yet

**Comment by antobinary** [comment]
Thanks for giving it a try! We'll take a look into this as part of 2.4-betaX

**Comment by cod3r0k** [comment]
Dear @antobinary , I test and found that we have also this issue in the `2.3.9` revision.
