### ISSUE TITLE
"Allow all guests" does not allow a guest to join

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/bigbluebutton#12850]
**Describe the bug**
"Allow all guests" does not allow a guest to join the meeting, but "Allow all authenticated" does.

**To Reproduce**
1. Go to 'https://demo.bigbluebutton.org'
2. Create a room and enable "Require moderator approval before joining"
3. Start the room
4. Open a private tab/window and join the room. You get the message "Please wait for a moderator to approve you joining the meeting."
5. In the authenticated session click "Allow all guests"
6. Verify that the guest session is still in the "waiting" state.
7. Click "Allow all authenticated".
8. Now the guest is allowed to join.

**Expected behavior**
The unauthenticated user should be able to join the meeting.

**Actual behavior**
The unauthenticated user seems to be treated as authenticated, not as "guest".

**Additional context**
My understanding is that a "guest" refers to the opposite of "authenticated" and means "not logged into in the frontend". It seems like others were confused/unsure about this too. #9099 #9651

**Comment by antobinary** [comment]
Hi @hex-m 

Was this on version 2.4 by any chance? (client build ~1332)? Right now demo pool has both 2.3 and 2.4 servers. We just fixed some guests troubles on 2.4 - #12875

**Comment by hex-m** [comment]
We noticed the problem on our local server. I just verified that it still exists in `2.3.9`. I just went to `demo.bigbluebutton.org` to make sure it's not a problem with our system/configuration.

Doing more tests today I noticed something else:

"Allow all guests" works as expected when I activate "Remember choice".

**Comment by pedrobmarin** [comment]
Hmmm, this might not be a bug. Just another "authenticated" thing that confuses everyone.

**Comment by hex-m** [comment]
Digging deeper, it seems that Greenlight does not set the `guest` parameter to `true` in the join call although the `userID` indicates that a user is a guest. (e.g. `userID=gl-guest-35aee6d35a3e00c1eb5bcbb9`)

So currently no user coming from Greenlight should be identified as a guest. In that case it is even more interesting, that

> "Allow all guests" works as expected when I activate "Remember choice".

The main problem seems to be on the Greenlight side. https://github.com/bigbluebutton/greenlight/pull/1417/commits/ba443d329e1985ab2c37c07b0acfe2cc533406aa looks like a possible fix.

**Comment by pedrobmarin** [comment]
So, as I mentioned before, not a bug. All users coming from greenlight are not guest-users and that's intentional. The guest param should never be used by anyone unless you disable the `authenticatedGuests` at bbb-web.

**Comment by hex-m** [comment]
So I close this as the original problem is not a bug.

But it's still confusing UX.

![Screenshot from 2021-08-03 15-05-47](https://user-images.githubusercontent.com/16013327/128021000-7a42ff67-0947-4fc7-aa68-e060038e0080.png)

The first button does the same thing as the third one. The second button does nothing (at least when you use Greenlight).

In the "Guest Policy"-Dialog there is no differentiation between guest and authenticated. It's unclear to me if those buttons accept/deny everyone or just "guests".

![Screenshot from 2021-08-03 15-23-25](https://user-images.githubusercontent.com/16013327/128022823-de3d8245-5dc6-42f3-925b-1f9bd743e463.png)

Also, if the request gets denied, the requesting user gets a 

> Guest denied of joining the meeting.

which would suggest that the user was a "guest".

Thanks for your help and the discussion!

**Comment by pedrobmarin** [comment]
Yeah, I agree 100% this is confusing. When I made the `authenticatedGuests=false` proposal I fixed all those UI caveats. Not sure if greenlight will ever use it tho.
