### ISSUE TITLE
[2.4-rc5] Virutal background blur sticky if enabled once

### ISSUE THREAD

**Issue by timm2k** [bigbluebutton/bigbluebutton#13796]
**Describe the bug**
After using a virutal background I can not switch to *no virtual background* in a running session. If no virtual background is selected background is blurred. Webcam preview is fine all time.

**To Reproduce**
1. Start a session with BBB 2.4 RC5
2. Start sharing your webcam with a virtual background
3. Stop sharing your webcam
4. Start sharing your webcam again without selecting a virtual background
5. Webcam background is blurred

**Expected behavior**
Webcam background is not blurred if not selected.

**Actual behavior**
Webcam background is blurred without selection
This is sticky to the running session. To reset this you need to create a new session.
Page refresh or reload even with dropping cache does not solve this.
Webcam preview is fine all time.

**BBB version:**
`BigBlueButton Server 2.4-rc-5 (2697)`

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome 96.0.4664.45, Firefox 94

**Comment by timm2k** [comment]
`2.4-rc-5` is working fine in this point.

**Comment by schrd** [comment]
This issue is only triggered if you have one webcam. If you have more webcams it is possible to turn off blur/background images. With one webcam blur is selected if you choose disable in the share webcam dialog

**Comment by Superjamp** [comment]
I've got a very similar problem:
1. start a session with BBB 2.4 RC5
2. select a virtual background
3. deselect virtual background
4. start sharing your webcam
5. webcam background is blurred

**Comment by schrd** [comment]
I think this is fixed with https://github.com/bigbluebutton/bigbluebutton/pull/13818
I cannot reproduce it in a build from a few minutes ago.

**Comment by JoVictorNunes** [comment]
This is still reproducible:

1. Open Video Preview.
2. Select any virtual background and start sharing.
3. Stop sharing.
4. Open Video Preview again and select None (you must click None).
5. Start sharing and the camera is blurred.

**Comment by prlanzarin** [comment]
#13818 has no relation with this.

**Comment by prlanzarin** [comment]
Fixed in #13822
