### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by pachainti** [bigbluebutton/bigbluebutton#13965]
Hi,
thank you very much with your work. The latest release v2.4 is great and it has an experimental support of mediasoup SFU.
The [documentation page](https://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support) is not up to date. What is the current maximum number of users per conference?
Moreover, docs [here](https://docs.bigbluebutton.org/) and [here](https://github.com/bigbluebutton/bbb-install#bbb-install) (still v2.3)  are not up to date too.

**Comment by antobinary** [comment]
I just updated bbb-install.sh https://github.com/bigbluebutton/bbb-install/pull/461
The PR for the docs website will follow

**Comment by antobinary** [comment]
I just updated the docs website https://github.com/bigbluebutton/bigbluebutton.github.io/pull/338

**Comment by antobinary** [comment]
Thanks again for the heads up! We're going through all places we need to update the info but it's taking longer than expected. If you come accross other obsolete spots, please notify us

**Comment by pachainti** [comment]
Hi, thank you for the fast correction. I still see an old version [here](https://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support), maybe the current maximum number of users per conference could also be increased (hopefully).

**Comment by antobinary** [comment]
Hi again!
`"As of BigBlueButton 2.3,..."` - I think this is fine - it's still correct.

Regarding the number of users per server - ideally there'd be a thorough test on a number of such servers so we can reliably specify a number. 150 seems conservative, and due to lack of reliable data, I'd rather stick with the conservative estimate.

We welcome feedback from the community - perhaps someone can help measure this and provide the results...
