### ISSUE TITLE
disableRecordingDefault=true not working

### ISSUE THREAD

**Issue by nephilim75** [bigbluebutton/bigbluebutton#14010]
Hello

I am running version 2.4 on Ubuntu 18.04 as recommended. I am trying to disable the recording of sessions by default. So I changed the line in `bigbluebutton.properties` to `disableRecordingDefault=true`. I restarted BBB with `bbb-conf --restart`.

But `bbb-record --list` still shows freshly recorded sessions.

I now work around by using a cron job deleting all recorded sessions on regular basis but I want to haven't them recorded in general. I would like to avoid recording at all.

Kind regards
//neph

**Comment by GuiLeme** [comment]
Confirmed! I will run some more tests and start implementing, great catch, thanks for reporting.

This is not happening to 2.5.x (I will make some research on how it was fixed on 2.5).

**Comment by GuiLeme** [comment]
Hey, @nephilim75, I am sorry, I commented sometime ago that I could reproduce this bug, but actually, I changed the code files and misplaced the config. In fact I couldn't reproduce the error once I've changed the config correctly. Could you give us more information on the bug? Such as `bbb-web` logs.

**Comment by antobinary** [comment]
Let's reopen if more info is provided and still reproducible on BBB 2.4.7 (latest right now)

**Comment by nephilim75** [comment]
I am now running version 2.5 with Greenlight. I have disabled recording in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`:
```
# Disable recording by default.
#   true - don't record even if record param in the api call is set to record
#   false - when record param is passed from api, override this default
disableRecordingDefault=true
```

`bbb-conf --restart`

Once I started a conference, the recording button is disappeared but it is recording by default. Once the meeting is ended and I check for records with `bbb-record --list`, recorded sessions will be listed:

```
root@bbb250-OS2004:~# bbb-record --list
Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
f401e4b321371240c5a9b62421d9f900ddc7b7fc-1673257375906  Mon 09 Jan 2023 09:42:55 AM UTC  X                 12
f401e4b321371240c5a9b62421d9f900ddc7b7fc-1673257178498  Mon 09 Jan 2023 09:39:38 AM UTC  X                 12
f401e4b321371240c5a9b62421d9f900ddc7b7fc-1673256784378  Mon 09 Jan 2023 09:33:04 AM UTC  X                 12
f401e4b321371240c5a9b62421d9f900ddc7b7fc-1673256055075  Mon 09 Jan 2023 09:20:55 AM UTC  X                 12
f401e4b321371240c5a9b62421d9f900ddc7b7fc-1673255812443  Mon 09 Jan 2023 09:16:52 AM UTC  X                 12
```

Looks like the issue is still not solved.

Kind regards
//neph

**Comment by antobinary** [comment]
Thanks for reporting this @nephilim75 
Let's continue the conversation in your newly opened #16418
