### ISSUE TITLE
[2.6rc2] blank first slide in presentation

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#16680]
**Describe the bug**
When I start a meeting, sometimes the first slide in the presentation is blank. It looks like that this only happens to the first person joining the meeting. Unfortunately it is not 100% reproducible but happening in about 50% of the meetings I start.

**To Reproduce**
1. Start a meeting on a 2.6 server
2. First slide is blank
3. next slides are not blank, if you resize the window, you'll see the content of the slide. If you resize back to the original size, you'll see the blank slide again
4. switching to another presentation and switching back does not fix this

**BBB version:**
2.6 rc2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox 102 ESR

**Additional context**
The effect is independent from the window size. I tried to investigate this using the browser developer tools. I am not 100% sure but it seems like the effect depends on the loading order of  the slide SVGs. If the slides are loaded in the order `3-2-1` the effect does not appear. If they are loaded in the order `2-1-3` it appears.

**Comment by antobinary** [comment]
Thanks for reporting! Do you know if you see the same if the first joiner is on Chrome or other browser?
We had similar issues that were addressed recently -- the client would load with max zoom into a [white] corner, so the entire slide looked empty. Please check the zoom levels.
Also, are you able to attach/send over some specific presentation that it happened with?

**Comment by schrd** [comment]
I was not able to reproduce this in chromium, however the environment is a bit different. I did the chromium tests from home and the firefox tests at the office which has a gigabit LAN connection to the BBB server. I never managed to receive the first slide before other slides at home, likely because network speed does not allow this.

The document is available at https://davis.hrz.tu-chemnitz.de/default.pdf

**Comment by schrd** [comment]
I played around with developer tools in Firefox. When I change the scale of the `data-testid="layer"` Element, the slide is either blank or not. When the meeting was started, the scale value was `0.9` → slide blank. When I change it to `0.8` → slide is visible (but too small of course).

Value `0.9`:

![Bildschirmfoto von 2023-05-08 21-41-51](https://user-images.githubusercontent.com/179952/236919406-bf588368-2f27-4a21-a135-ef9f51e910a4.png)
![Bildschirmfoto von 2023-05-08 21-41-58](https://user-images.githubusercontent.com/179952/236919504-dcc0d10b-9686-435e-9e54-af86297583e1.png)

Value `0.8`:
![Bildschirmfoto von 2023-05-08 21-42-09](https://user-images.githubusercontent.com/179952/236919400-89184045-9593-48f3-8ab3-8c354381df44.png)
![Bildschirmfoto von 2023-05-08 21-42-16](https://user-images.githubusercontent.com/179952/236919510-51ff1cbd-7a8e-433e-9f20-d52045292ea4.png)

**Comment by antobinary** [comment]
Great job @schrd ! This should help resolve the issue :crossed_fingers:

**Comment by ramonlsouza** [comment]
@schrd are you able to reproduce this in latest 2.6?

It looks like the issue fixed by https://github.com/bigbluebutton/bigbluebutton/pull/17357 (merged in BBB 2.6.1)

**Comment by schrd** [comment]
> @schrd are you able to reproduce this in 2.6.6?
> 
> It looks like the issue fixed by #17357 (merged in BBB 2.6.1)

Unfortunately still reproducible. I built fresh 2.6.7 packages and it still shows up. I am pretty sure this is not related to our setup or something else as the effect was also visible during today community meeting when @antobinary uploaded the screenshot of the 2.6.7 release notes. I "fixed" it by changing the size of the cameras.

**Comment by schrd** [comment]
It looks like this one is also fixed by #17983

**Comment by schrd** [comment]
Unfortunately this bug still exists in 2.6.9. We see this from time to time in Firefox.

**Comment by antobinary** [comment]
Possibly you're seeing what's described in https://github.com/bigbluebutton/bigbluebutton/issues/17969#issuecomment-1568087349 ? i.e. https://github.com/bigbluebutton/bigbluebutton/issues/16826 ?

**Comment by schrd** [comment]
No its different. The whole slide is blank. It is still there in 2.6.12 and I also saw this in 2.7 rc
