### ISSUE TITLE
[2.6 tldraw] changing fonts for Asian text does not make difference

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#17245]
**Describe the bug**
Currently four fonts are selectable for alphabet. But for Asian text, the font selection does not make a lot of difference at least for Japanese, Korean, and Thai

**To Reproduce**
1. write text in Japanese
2. try changing font by style menu

**Expected behavior**
Asian fonts should be related to the alphabet fonts currently implemented, and users can select the text style.

**Actual behavior**
No change in the text style.

**Screenshots**
https://user-images.githubusercontent.com/45039819/227687907-bf86b5ce-4421-4f5f-b43e-9448190535ce.mov

**BBB version:**
Latest (test26 server)

**Desktop (please complete the following information):**
 - Brave
 - MacOS

**Additional context**
I thought somebody already submit the issue, but I cannot spot it out.
Tldraw itself has the same problem, which seems to have been solved in the beta version of new tldraw. 
On the other hand I thought this issue was fixed at some RC of BBB2.6, if I remember correctly. I am a bit confused...

**Comment by hiroshisuga** [comment]
@antobinary, I would love to contribute. Where in the source code should I modify?

**Comment by antobinary** [comment]
Hi @hiroshisuga 
Apologies for seeing this so late. We were pulling newer version from tldraw in BBB 2.6 and I hope this was resolved in 2.6/2.7. The source code would have been tldraw itself.
In BBB 3.0 (work in progress) we build upon the next generation tldraw v2 (~circa alpha.18-19) which should be behaving much better.

**Comment by hiroshisuga** [comment]
Hi @antobinary , yes, I've seen the improvement. Some fonts still don't look so different, but it's much better now. Thanks!
