### ISSUE TITLE
Sometimes video, audio and screensharing crash for all participants in a room

### ISSUE THREAD

**Issue by herzkerl** [bigbluebutton/bigbluebutton#20175]
**Describe the bug**
Sometimes, for some sessions, video, audio and screensharing get disconnected/crashes at the same time for **all** participants in the room—regardless of OS, browser, etc.

This happened with v2.5, then 2.6, now running 2.7.6 (584) and it is still happening.
It can happen in smaller groups of 4 or 5 participants, but also in larger groups of 40+ participants.

We have yet to find a common denominator...

**To Reproduce**
Unknown

**Actual behavior**
Video, audio, screensharing get disconnected/crashed for all participants in the room.

**Comment by GhaziTriki** [comment]
Hello @herzkerl,

Can you please give more details about the server hosting BigBlueButton. Do you have any error logs to share?

**Comment by herzkerl** [comment]
Hello @GhaziTriki,

it's a virtual machine on our Proxmox cluster (x86-64-v3, 4 cores, 16 GB memory without ballooning, NVMe storage). We host several other machines like this one, that do not have (or at least not communicate to us) those issues.

Unfortunately I have yet to find anything useful in the logs—is there any particular log/service that I should take a look at?

Thanks!

**Comment by herzkerl** [comment]
> If you're not comfortable with attaching them publicly, send them to `prlanzarin at mconf dot com`

Done.

```
BigBlueButton Server 2.7.6 (584)
                    Kernel version: 5.4.0-177-generic
                      Distribution: Ubuntu 20.04.6 LTS (64-bit)
                            Memory: 16380 MB
                         CPU cores: 8

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.domain.tld
                defaultGuestPolicy: ALWAYS_ACCEPT
              defaultMeetingLayout: CUSTOM_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: bbb.domain.tld
                              port: 80, [::]:80127.0.0.1:82 http2 proxy_protocol, [::1]:82 http2127.0.0.1:81 proxy_protocol, [::1]:81

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 123.123.123.123
                   external_rtp_ip: 123.123.123.123
                   external_sip_ip: 123.123.123.123

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: 123.123.123.123:5066
                       wss-binding: 123.123.123.123:7443

UDP port ranges

                        FreeSWITCH: 16384-24576
                           kurento: 24577-32768
                    bbb-webrtc-sfu: 24577-32768
                    bbb-webrtc-recorder: 24577-32768

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.domain.tld
                 playback_protocol: https
                            ffmpeg: 4.2.7-0ubuntu0.1

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 123.123.123.123
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (bbb-webrtc-sfu)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (bbb-webrtc-sfu - override)
    mediasoup.webrtc.*.announcedIp: 123.123.123.123
  mediasoup.plainRtp.*.announcedIp: 123.123.123.123
                        kurento.ip: 123.123.123.123
                       kurento.url: ws://127.0.0.1:8888/kurento
                 freeswitch.sip_ip: 123.123.123.123
                  recordingAdapter: Kurento
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/etc/bbb-webrtc-recorder/bbb-webrtc-recorder.yml (bbb-webrtc-recorder)
/etc/bigbluebutton/bbb-webrtc-recorder.yml (bbb-webrtc-recorder - override)
               debug: false
               recorder.directory: /var/lib/bbb-webrtc-recorder

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 249
                        kurentoUrl: wss://bbb.domain.tld/bbb-webrtc-sfu
            defaultFullAudioBridge: fullaudio
           defaultListenOnlyBridge: fullaudio
                    sipjsHackViaWs: true


# Potential problems described below
```

**Comment by clementgoclock** [comment]
If is still happening can you check if freeswitch using a lot of interrup/context switching ? Do you monitor with netdata and see some drop into metrology logging (indicating cpu overload). Or cpu softlock on dmesg ?

Telling you this because we're experimeting something similar, with the things i just mentionned. 

Virtual Machine or metal ? 

AMD EPYC 7543 32-Core here and VM under KVM, bbb 2.7.6

**Comment by caniwi** [comment]
We have users raising similar issue with screenshare buffer/hang/load/restart sporadically during a call.

This is our bbb-conf --check 

```
 bbb-conf --check

BigBlueButton Server 2.7.12 (732)
                    Kernel version: 5.4.0-192-generic
                      Distribution: Ubuntu 20.04.6 LTS (64-bit)
                            Memory: 16378 MB
                         CPU cores: 16

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bigbb.ourdomain.ltd
                defaultGuestPolicy: ALWAYS_ACCEPT
              defaultMeetingLayout: CUSTOM_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: bigbb.ourdomain.ltd
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 10.10.10.10
                   external_rtp_ip: 123.123.123.123
                   external_sip_ip: 123.123.123.123

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: :7443

UDP port ranges

                        FreeSWITCH: 16384-24576
                           kurento: 24577-32768
                    bbb-webrtc-sfu: 24577-32768
                    bbb-webrtc-recorder: 24577-32768

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bigbluebutton.example.com
                 playback_protocol: http
                            ffmpeg: 4.2.7-0ubuntu0.1

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 123.123.123.123
                          protocol: https

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (bbb-webrtc-sfu)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (bbb-webrtc-sfu - override)
    mediasoup.webrtc.*.announcedIp: 123.123.123.123
  mediasoup.plainRtp.*.announcedIp: 123.123.123.123
                        kurento.ip: 10.10.10.10
                       kurento.url: ws://127.0.0.1:8888/kurento
                 freeswitch.sip_ip: 10.10.10.10
                  recordingAdapter: Kurento
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/etc/bbb-webrtc-recorder/bbb-webrtc-recorder.yml (bbb-webrtc-recorder)
/etc/bigbluebutton/bbb-webrtc-recorder.yml (bbb-webrtc-recorder - override)
               debug: false
               recorder.directory: /var/lib/bbb-webrtc-recorder

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 331
                        kurentoUrl: wss://bigbb.ourdomain.ltd/bbb-webrtc-sfu
            defaultFullAudioBridge: fullaudio
           defaultListenOnlyBridge: fullaudio
                    sipjsHackViaWs: false

/etc/bigbluebutton/turn-stun-servers.xml (STUN Server)
                              stun: stun1.ourdomain.ltd:3478

/etc/bigbluebutton/turn-stun-servers.xml (STUN Server)
                              stun: stun2.ourdomain.ltd:3478


# Potential problems described below

# Warning: The setting of 123.123.123.123 for proxy_pass in
#
#    /usr/share/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.10.10.10).
# (This is OK if you've manually changed the values)

```

**Comment by caniwi** [comment]
From the above bbb-conf --check output it appears that the settings in our /etc/bigbluebutton/recording/recording.yml is not overriding the /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml which is odd.

**Comment by caniwi** [comment]
Just adding that we have logs captured from a moment when the issue was occurring.  Also whether this is being actively monitored and reviewed.

**Comment by caniwi** [comment]
I have sent a link where you can download the zip file from. The incident involved screen share would buffer/hang/load/restart sporadically during the call.

The meeting occurred between 09:30 - 11:00 2024-08-27

We have had numerous other meetings where video, voice and screen share have been unreliable.

**Comment by caniwi** [comment]
This is still happening on 2.7.13.  Any insights you can share would be appreciated.

**Comment by caniwi** [comment]
@prlanzarin thanks for having the review. We have been doing some network tests and not found anything significant. We are interested in implementing feature #21008 as we just put 2.7.14 into production this morning.

Could you confirm the updates should be as follows:

For /etc/bigbluebutton/bbb-webrtc-sfu/production.yml
 ```
allowIceRestart: true
```


For /etc/bigbluebutton/bbb-html5.yml

```
public:
  layout:
    hidePresentationOnJoin: true
  kurento:
    wsUrl: wss://<redacted>/bbb-webrtc-sfu
    restartIce:
      audio:
        enabled: true
        retries: 1
      video:
        enabled: true
        retries: 3
      screenshare:
        enabled: true
        retries: 3
```

**Comment by herzkerl** [comment]
This is still happening on 2.7.16, is there anything else we can provide?

```yaml
    forceRelayOnFirefox: true
    restartIce:
      audio:
        enabled: true
        retries: 1
      video:
        enabled: true
        retries: 3
      screenshare:
        enabled: true
        retries: 3
