### ISSUE TITLE
[3.0] Blank white screen for recordings at mobile devices

### ISSUE THREAD

**Issue by Zvangi** [bigbluebutton/bigbluebutton#23299]
**Describe the bug**
Recordings show as blank white screen on mobile devices. It plays fine for few seconds and as soon as there is a document involved or you skip forward, screen goes all white. This happens on full screen recording view.

**To Reproduce**
1. Open a recording with webcam, chat and document involved
2. Skip to a part where document is being streamed and drawn on or just skip forward
3. Screen goes blank instantly

**Expected behavior**

Skip forward normall without breaking.

**Smartphone (please complete the following information):**
 - Device: Mi 12
 - OS: Android 15
 - Browser: Chrome
 - Version 136.0.7

**Additional context**

Tested on various devices such as iphone 13 pro max, safari, other chrome versions and so on.

I didn't encounter this on previous versions such as 2.7.9 (with same mi12 device)

This is really important as a lot of viewers use mobile devices.

**Comment by antobinary** [comment]
Hi @Zvangi 

The issue you report was fixed a couple of days ago in https://github.com/bigbluebutton/bbb-playback/pull/300
The fix will ship with BBB 3.0.9.
Wondering if you can view this recording on your Mi 12 device? https://dev30.bigbluebutton.org/playback/presentation/2.3/b4df901682724a6d37f5cec61a20ff193bcb3e08-1748624894543

**Comment by Zvangi** [comment]
Yes, issue happens on this link also. I tried in incognito too.

> Hi [@Zvangi](https://github.com/Zvangi)
> 
> The issue you report was fixed a couple of days ago in [bigbluebutton/bbb-playback#300](https://github.com/bigbluebutton/bbb-playback/pull/300) The fix will ship with BBB 3.0.9. Wondering if you can view this recording on your Mi 12 device? https://dev30.bigbluebutton.org/playback/presentation/2.3/b4df901682724a6d37f5cec61a20ff193bcb3e08-1748624894543

**Comment by Zvangi** [comment]
Just an update.

I upgraded my BBB version to 3.1-beta and issue still remains with recordings. Should I re-process my recordings? 

> Hi [@Zvangi](https://github.com/Zvangi)
> 
> The issue you report was fixed a couple of days ago in [bigbluebutton/bbb-playback#300](https://github.com/bigbluebutton/bbb-playback/pull/300) The fix will ship with BBB 3.0.9. Wondering if you can view this recording on your Mi 12 device? https://dev30.bigbluebutton.org/playback/presentation/2.3/b4df901682724a6d37f5cec61a20ff193bcb3e08-1748624894543

**Comment by antobinary** [comment]
Hi! I don't think reprocessing would help.
I am trying to reproduce the error in an environment where I could see the console logs. Are you able to share your logs when opening the recording above? Perhaps in dev mode?

**Comment by Zvangi** [comment]
Im getting this as a console output. Cannot read properties of null (reading 'currentTime') keeps increasing rapidly too. @antobinary 

You can test it on your end using this recording

https://bbb3.yazilimgemisi.com/playback/presentation/2.3/6a8a61140df11c7179be9ff15c0704bd37f047f9-1748527071823

![Image](https://github.com/user-attachments/assets/5404944d-af5e-46cb-85a5-73a374443aee)

> Hi! I don't think reprocessing would help. I am trying to reproduce the error in an environment where I could see the console logs. Are you able to share your logs when opening the recording above? Perhaps in dev mode?

**Comment by antobinary** [comment]
Thanks! I can see the logs indeed!

![Image](https://github.com/user-attachments/assets/e3254ce0-9b0f-48d1-a905-0ba3973f187c)

**Comment by antobinary** [comment]
With https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.3.5 the playback no longer crashes. ~~However, the whiteboard is missing.~~

https://github.com/user-attachments/assets/48e60efc-28bc-409d-affc-caf4919d1ac7

**Comment by Zvangi** [comment]
Can you share the recording link?

> With https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.3.5 the playback no longer crashes. However, the whiteboard is missing.
> 
>  Screencast.from.2025-06-04.15-47-06.mp4

**Comment by antobinary** [comment]
Same link as above https://dev30.bigbluebutton.org/playback/presentation/2.3/b4df901682724a6d37f5cec61a20ff193bcb3e08-1748624894543

**Comment by Zvangi** [comment]
I can see the drawing after switching to "presentation" from top right icon (two arrows)

> Same link as above https://dev30.bigbluebutton.org/playback/presentation/2.3/b4df901682724a6d37f5cec61a20ff193bcb3e08-1748624894543

**Comment by antobinary** [comment]
Excellent! Thanks for confirming! This fix will be part of BBB 3.0.9 (to be released within a few days).

**Comment by Zvangi** [comment]
Thank you for resolving it @antobinary @germanocaumo Can't wait for the release. Since I upgraded to 3.1, will this also fix it on 3.1 ?

> Excellent! Thanks for confirming! This fix will be part of BBB 3.0.9 (to be released within a few days).

**Comment by antobinary** [comment]
The fix will be in BBB 3.1.0-beta.2 (no release date scheduled yet).
If you are running this on production, BBB 3.0 is the current recommendation. BBB 3.1 is still in beta stage.

**Comment by Zvangi** [comment]
I assume I can't use bbb-install to go back to 3.0 so im cooked :(

> The fix will be in BBB 3.1.0-beta.2 (no release date scheduled yet). If you are running this on production, BBB 3.0 is the current recommendation. BBB 3.1 is still in beta stage.

**Comment by antobinary** [comment]
I am not aware of a way to safely and reliably revert. If this is a server you would otherwise lose, I suggest you back up the recordings. Then you could try `sudo apt purge bigbluebutton bbb-*`, then change the contents of `/etc/apt/sources.list.d/bigbluebutton.list` replacing `jammy-310` with `jammy-300`, and then re-running the bbb-install you used to install 3.0 (i.e. .... -v jammy-300 ...)

I can't guarantee it would work flawlessly but there's a chance...

The check to confirm there's no 3.1 packages would be to not have anything 3.1 in `sudo dpkg -l | grep bbb-`. You may need to purge the remaining ones and then re-running bbb-install.sh if you detected any later on.

**Comment by Zvangi** [comment]
Since it's a VM in my dedicated, I will take a backup of server before trying this. I will just wait the second beta release if it doesn't work out. Thank you so much tho.

> I am not aware of a way to safely and reliably revert. If this is a server you would otherwise lose, I suggest you back up the recordings. Then you could try `sudo apt purge bigbluebutton bbb-*`, then change the contents of `/etc/apt/sources.list.d/bigbluebutton.list` replacing `jammy-310` with `jammy-300`, and then re-running the bbb-install you used to install 3.0 (i.e. .... -v jammy-300 ...)
> 
> I can't guarantee it would work flawlessly but there's a chance...
> 
> The check to confirm there's no 3.1 packages would be to not have anything 3.1 in `sudo dpkg -l | grep bbb-`. You may need to purge the remaining ones and then re-running bbb-install.sh if you detected any later on.

**Comment by Zvangi** [comment]
This worked. I tested it for a new meeting and works fine for now. Recording works properly and old recordings are now working on mobile too.

> I am not aware of a way to safely and reliably revert. If this is a server you would otherwise lose, I suggest you back up the recordings. Then you could try `sudo apt purge bigbluebutton bbb-*`, then change the contents of `/etc/apt/sources.list.d/bigbluebutton.list` replacing `jammy-310` with `jammy-300`, and then re-running the bbb-install you used to install 3.0 (i.e. .... -v jammy-300 ...)
> 
> I can't guarantee it would work flawlessly but there's a chance...
> 
> The check to confirm there's no 3.1 packages would be to not have anything 3.1 in `sudo dpkg -l | grep bbb-`. You may need to purge the remaining ones and then re-running bbb-install.sh if you detected any later on.

**Comment by antobinary** [comment]
Awesome!! Thanks for the feedback!
