### ISSUE TITLE
[3.0] presentation cropped on right side.

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#23726]
suddenly 1 day several servers users reported default presentation is cropped.
bbb-conf --restart is fixing this, so I think it's related to server's cache.

new uploaded presentation has all text on screen but presentation block is still same narrow size.

<img width="1582" height="897" alt="Image" src="https://github.com/user-attachments/assets/acdb0446-d48e-421e-811b-20dd5278a6b6" />

all servers reported for now has version 3.0.12, but it happened before with version 3.0.4 too.

**Comment by Heinivb** [comment]
Hi, we had a similair issue (we were on BBB 3.0.6), after updating to 3.0.13 the issue was resolved for us

**Comment by amg-web** [comment]
@Heinivb issue resolved by simple `bbb-conf -restart`
but it  would be better to avoid it in future

**Comment by MrTux86** [comment]
same problem with version 3.0.16.
It seems like not every file got this issue.
Some uploads work and are shown correctly.
Restarting the bbb services with "bbb-conf --restart" does not solve the problem

Edit:
I'm getting quite a lot of errors:
/var/log/bigbluebutton/bbb-web.log:2025-10-11T13:39:52.991+02:00 ERROR o.b.p.h.AbstractCommandHandler - [imgresolution-/var/bigbluebutton/MEETING-ID/ANOTHER-ID/ANOTHER-ID/svgs/slide7.svg] identify: delegate failed `'rsvg-convert' -o '%o' '%i'' @ error/delegate.c/InvokeDelegate/1966.

**Comment by Lutice** [comment]
Same problem as @MrTux86 on 3.0.16 16/9 works on some servers, but not on all. Presentation cropped to 4/3 

with same error message : 
```
2025-10-25T09:09:18.671+02:00 ERROR o.b.p.h.AbstractCommandHandler - [imgresolution-/var/bigbluebutton/9b6211ec441d6d423a295bf295656f89ff21c3ca-1761376156258/9b6211ec441d6d423a295bf295656f89ff21c3ca-176137615625
8/6c80e751ba837ea38ecc49b716373aac3b625166-1761376156298/svgs/slide2.svg] identify: delegate failed `'rsvg-convert' -o '%o' '%i'' @ error/delegate.c/InvokeDelegate/1966.
identify: unable to open file `/tmp/magick-6Gwx_E1DJ6FDlecQJKPjPzLshPsVvnrB': No such file or directory @ error/constitute.c/ReadImage/619.

```

<img width="804" height="646" alt="Image" src="https://github.com/user-attachments/assets/63e7b7e3-9c3c-4ee1-be54-b11e2e55e16a" />

**Comment by Lutice** [comment]
@MrTux86 could you try this command on your server : 
convert -list format | grep SVG
normally you must see something like that :

<img width="674" height="61" alt="Image" src="https://github.com/user-attachments/assets/db06b810-8cca-44cc-9b33-11c9f56109ff" />

But on our server we have the same error like you nothing appear. We continue to investigate.

**Comment by MrTux86** [comment]
Hi Lutice.

On servers where the conversion works, I get the exact output you posted.
On servers, where the error occurs, I don't get any of those svg's.

I tested a bit and maybe found a solution:

If I install librsvg2-bin with

`apt install librsvg2-bin
`

the conversion seems to work again.
I don't know if that may bug with anything from the bbb server after some time.

**Comment by Lutice** [comment]
@MrTux86 effectively when you install this paquet the convert run. But something is strange, on the others servers where the convert seems run, this paquet was not install.
And after the paquet installation the command : convert -list format | grep SVG 
continue to return : nothing

**Comment by MrTux86** [comment]
yeah, noticed that too.
no svg output, but conversion works.

Seems like "librsvg2-bin" enables the "rsvg-convert" command.
The "normal" bbb install through the bash script seems to work with "convert" and the corresponding svg libraries from ImageMagick.
Maybe there is a `rsvg-convert` symlink to `convert` on systems where the convert works correctly.

Edit:
Just checked, there is no symlink from rsvg-convert to convert.
Looks like the needed "libraries" aren't installed during the install/upgrade process or they somehow got lost.

**Comment by Lutice** [comment]
another strange thing is when you use this command : 
`identify -list configure | grep svg`
In two cases ImageMagick is compiled without rsvg
<img width="1918" height="206" alt="Image" src="https://github.com/user-attachments/assets/0058c1e7-6b84-4ed5-8c54-dae41d9d245e" />

**Comment by MrTux86** [comment]
I think I found the cause of the convert problem:

If you install:

`apt install libmagickcore-6.q16-6-extra`

the `convert -list format | grep SVG` comand shows the correct output.

On the server, where the conversion worked, this extra package is installed, on those servers with the crop problem, it is missing.

**Comment by Lutice** [comment]
@MrTux86 good catch ... Same thing on my configuration.
2 solutions for 1 problem ;-) but I think the last is better than the first.
The question now is why libmagickcore-6.q16-6-extra was not installed by default during installation :
Resume to solve :
check the format supported by convert 
`convert -list format | grep SVG`
if nothing appear, check if magickcore extra is installed
`apt list --installed | grep magickcore`
normally 2 lines appear
<img width="1172" height="52" alt="Image" src="https://github.com/user-attachments/assets/6abf7438-2dc4-494c-a467-e23cbd05a9c1" />
If only one without extra, install the extra package
`apt install libmagickcore-6.q16-6-extra`
check again
`convert -list format | grep SVG`
The result must be like this
<img width="697" height="65" alt="Image" src="https://github.com/user-attachments/assets/08a09c0a-e498-4727-87fa-8e018844ae96" />

**Comment by amg-web** [comment]
`libmagickcore-6.q16-6-extra` was installed on the server, and the issue was present.

if the issue was related to `libmagickcore-6.q16-6-extra` it would never be fixed by `bbb-conf --clean`.
So I think it's related to cache

**Comment by MrTux86** [comment]
do you get any errors with `bbb-conf --watch` ?
If the libmagick package is missing, you will get a lot of conversion errors.

Would be interesting if there are errors when the package is installed but the cache somehow blocks the conversion

Edit:
On all of the servers I encountered the problem, the `libmagickcore-6.q16-6-extra` was missing and the error was resolved as soon as the package was installed.

**Comment by amg-web** [comment]
@MrTux86 
on debug logs I see many similar unrelated lines:

> Oct 30 13:55:03 bigbluebutton c53d2c369366[2118]: [f4c8f87a-86f0-4c89-8f79-df6119958dd4] actionpack (7.2.2.1) lib/action_dispatch/middleware/show_exceptions.rb:32:in \`call'
> Oct 30 15:47:24 bigbluebutton bbb-apps-akka[1424]: 2025-10-30T15:47:24.889Z DEBUG o.a.pekko.actor.RepointableActorRef - Aborting tcp connection to /127.0.0.1:44836 because of upstream failure: org.apache.pekko.http.impl.engine.HttpIdleTimeoutException: HTTP idle-timeout encountered, no bytes passed in the last 60 seconds. This is configurable by pekko.http.[server|client].idle-timeout.
> Oct 31 04:31:21 bigbluebutton c53d2c369366[2118]: [300d0816-352b-4477-b188-20eec72928d2] actionpack (7.2.2.1) lib/action_dispatch/middleware/show_exceptions.rb:32:in \`call'
> Oct 31 07:30:54 bigbluebutton bbb-fsesl-akka[1387]: java.net.ConnectException: Connection refused
> Oct 31 07:31:04 bigbluebutton bundle[1295]: SignalException: SIGTERM

and only 1 line that can be related (I did restart today):
> /var/log/bigbluebutton/bbb-web.log:2025-10-31T09:34:10.291Z ERROR o.b.p.h.AbstractCommandHandler - [office2pdf-41b64eabe420af0fde713f9686c81305505ea230-1761903155363-edffd770f86ca12d76d1311417bce1cbce20bcbc-1761903248449] Could not find platform independent libraries <prefix>

installed magic packets:
```
root@bigbluebutton:~# apt list --installed | grep magick

imagemagick-6-common/jammy-updates,jammy-security,now 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.5 all [installed,automatic]
imagemagick-6.q16/jammy-updates,jammy-security,now 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.5 amd64 [installed,automatic]
imagemagick/jammy-updates,jammy-security,now 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.5 amd64 [installed,automatic]
libmagickcore-6.q16-6-extra/jammy-updates,jammy-security,now 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.5 amd64 [installed]
libmagickcore-6.q16-6/jammy-updates,jammy-security,now 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.5 amd64 [installed,automatic]
libmagickwand-6.q16-6/jammy-updates,jammy-security,now 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.5 amd64 [installed,automatic]
```
