### ISSUE TITLE
Can't close Presentation Upload window after conversion fails

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#4224]
If your file conversion fails ( as described in #4223 ) - then there is no way of how the user can close the popup window.

You can still see the progress bar, an error message, but can't do anything to get out.
The only option in this case is to refresh the page.

![acdf4be1ec61ae3601a06d4c1c219d88](https://user-images.githubusercontent.com/9299997/29186684-3f1c7998-7ddb-11e7-9497-a4f82400961b.gif)

**Comment by ritzalam** [comment]
There's an X button on the upper right corner. Maybe it only shows when the mouse hovers on the window.

**Comment by ritzalam** [comment]
Tried it again and there's no X button. Perhaps it appeared when the box refreshed after another window was displayed on top of it.

**Comment by ritzalam** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/4233

**Comment by ffdixon** [comment]
Looks like the file upload dialog is still not showing the 'x'

**Comment by GhaziTriki** [comment]
The `X` is always shown and never hidden, instead of hiding it we are only enabliing/disbaling it.

**Comment by capilkey** [comment]
The "X" button also isn't in the tab order and can only be selected using a mouse. It's why I had added "Close" buttons to all of the popups. I'm going to have to add them back again.
