### ISSUE TITLE
Not able to perform webrtc call in Chrome with the flag Unified Plan enabled.

### ISSUE THREAD

**Issue by vkkkumar** [bigbluebutton/bigbluebutton#6414]
Go to Chrome://flags
Search for  "WebRTC: Use Unified Plan SDP Semantics by default" and enable it

Open BigBlueButton and perform a webrtc call.

There is an issue in the audio and video. After some time there is an error shown like " Detected the following WebRTC issue: Error 1010: ICE negotiation timeout. Do you want to try Flash instead?"

This works well without the flag enabled and also in Firefox 62.0.3 and later.

Refer Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=895820

**Comment by huibk** [comment]
Note that unified plan is scheduled to become default in Chrome 72 (february 2019), see https://webrtc.org/web-apis/chrome/unified-plan/ for details

**Comment by ffdixon** [comment]
Thanks for reporting this guys -- we'll take a closer look.

**Comment by capilkey** [comment]
I've sent in a PR that creates the RTCPeerConnection with "sdpSemantics:'plan-b'" so that Chrome will use plan-b instead of the default when it's switched to unified-plan. This will only be a stop gap until FreeSWITCH updates their SDP to be compatible with the new format.

Relevant FS bug report about the unified plan is here, https://freeswitch.org/jira/browse/FS-11470.

**Comment by henbos** [comment]
Howdy folks, I noticed that https://freeswitch.org/jira/browse/FS-11470 says it was fixed on Dec 26. Should Big Blue Button be updated to use Unified Plan?

**Comment by ffdixon** [comment]
We released [BigBlueButton 2.0-RC9](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.0-rc9) about an hour ago that has a fix for Plan B.  You can test on https://demo.bigbluebutton.org/.  If you update your server it should work as well.

Let us know if you encounter any issues.

**Comment by henbos** [comment]
It should work if you explicitly set it to Plan B, though I seem to experience "Plugin not supported" on linux and "ICE negotiation failed" on mac (regardless of SDP semantics) so I can't verify whether or not this works.

In any case, Unified Plan will soon be the default in Chrome and Safari, and Firefox already speaks Unified Plan, so switching to Unified Plan should be a future work item.

**Comment by capilkey** [comment]
Freeswitch still doesn't support the new format. The "fix" that is mentioned in the bug report is to set the SDP to "plan-b" as I've done. Until there's support for it on the server side there's nothing more we can do.
