### ISSUE TITLE
Help with coturn

### ISSUE THREAD

**Issue by dahalday** [bigbluebutton/bigbluebutton#7140]
I am trying to set up TURN/STUN to work with BBB but i cannot locate the file 
/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/spring/turn-stun-servers.xml

Using BBB 2.2 beta

Also can some one help with the variables in /etc/turnserver.conf.

The version install on Ubuntu 18 coturn server differs from the post. 

Kind Regards 
D

**Comment by ffdixon** [comment]
Thanks for pointing this out -- there was an old path in the documentation.  The correct path is `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`. We've updated the docs at

  http://docs.bigbluebutton.org/2.2/setup-turn-server.html#configure-bigbluebutton-to-use-the-coturn-server

so they now have the correct path.

**Comment by ffdixon** [comment]
> Also can some one help with the variables in /etc/turnserver.conf.

Which variable are you looking for.  Also, you can use `bbb-install.sh` to automate the setup of a coturn server, see

  https://github.com/bigbluebutton/bbb-install#install-a-turn-server

**Comment by dahalday** [comment]
This for the links to the scripts. The scripts work well and the files are configured as indicated , but the issues ice errors persist in some locations where  test.bigbluebutton.org work fine. .

**Comment by dahalday** [comment]
Hi

Is there a script to check to see if the big blue button server is picking up the Turn server. And how can if tell if the turn server is working. 

Also once coturn configured do we need to edit. /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini.

**Comment by mikhailnov** [comment]
There are 2 ways:
- Wireshark
- Console log in developer tools, see screenshot
![Снимок экрана_2019-03-31_23-18-59](https://user-images.githubusercontent.com/15802528/55294491-622cfe00-540b-11e9-81a6-154ab333788c.png)

P.S. I've seen that my turn server is not used, will write to https://github.com/bigbluebutton/bigbluebutton/issues/7141

**Comment by dahalday** [comment]
Dear Fred

Thanks for all the Help. The installation scripts are fantastic and put the information as they should but I still cannot connect.

The system works find on most networks except my work network. For home to home  testing it is ok.

Can you tell me what I am missing.

Please note below

Kind Regards
Darron Halliday

Turn server on firewall but almost all ports opened
Incoming
Action   Allowed IP           Protocol               Port(s)  Description
Allow     All                           TCP/UDP             80
Allow     All                           TCP/UDP             443
Allow     All                           TCP/UDP             49152-65535
Allow     All                           TCP/UDP             53
Allow     All                           TCP/UDP             123
Allow     All                           TCP/UDP             3478-19302
Allow     All                           UDP       161

BBB firewall

Incoming
Action   Allowed IP           Protocol
Allow     All                           TCP/UDP             80
Allow     All                           TCP/UDP             443
Allow     All                           TCP/UDP             7443
Allow     All                           TCP/UDP             8888
Allow     All                           TCP/UDP             5000-5100
Allow     All                           UDP       16384-32768


My Turner settings
# Example coturn configuration for BigBlueButton

# These are the two network ports used by the TURN server which the client
# may connect to. We enable the standard unencrypted port 3478 for STUN,
# as well as port 443 for TURN over TLS, which can bypass firewalls.
listening-port=3478
tls-listening-port=443

# If the server has multiple IP addresses, you may wish to limit which
# addresses coturn is using. Do that by setting this option (it can be
# specified multiple times). The default is to listen on all addresses.
# You do not normally need to set this option.
# listening-ip=62.151.176.229

# If the server is behind NAT, you need to specify the external IP address.
# If there is only one external address, specify it like this:
external-ip=62.151.176.229
# If you have multiple external addresses, you have to specify which
# internal address each corresponds to, like this. The first address is the
# external ip, and the second address is the corresponding internal IP.
#external-ip=172.17.19.131/10.0.0.11
#external-ip=172.17.18.132/10.0.0.12

# Fingerprints in TURN messages are required for WebRTC
fingerprint

# The long-term credential mechanism is required for WebRTC
lt-cred-mech

# Configure coturn to use the "TURN REST API" method for validating time-
# limited credentials. BigBlueButton will generate credentials in this
# format. Note that the static-auth-secret value specified here must match
# the configuration in BigBlueButton's turn-stun-servers.xml
# You can generate a new random value by running the command:
#   openssl rand -hex 16
use-auth-secret
static-auth-secret=8099463cfc344256e23ced7415dc2a33


Bigbluebutton settings

  GNU nano 2.5.3                         File: /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">

    <bean id="stun0" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:turnsunshinelearner.ddns.net"/>
    </bean>


    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="8099463cfc344256e23ced7415dc2a33"/>
        <constructor-arg index="1" value="turns:turnsunshinelearner.ddns.net:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="stunTurnService"
            class="org.bigbluebutton.web.services.turn.StunTurnService">
        <property name="stunServers">
            <set>
                <ref bean="stun0"/>
            </set>
        </property>
        <property name="turnServers">
            <set>
                <ref bean="turn0"/>
            </set>
        </property>
    </bean>
</beans>







Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by capilkey** [comment]
@dahalday, I would suggest changing your turn secret to something else and not publishing your secret to public places. Anyone could take the information and use your server.

One strange thing I noticed is that your TURN server seems to have Apache2 installed on it. The server used for coturn should be clean just like with normal BBB installs.

**Comment by dahalday** [comment]
Thanks for the Updates I will take your advice.

This is what worked for me

Clean Ubuntu 18.04 install

Setup a new Apache virtual host file in Apache's configuration directory:


Use your prefered method
or
https://www.digitalocean.com/community/tutorials/how-to-install-webmin-on-ubuntu-18-04

For example

sudo nano /etc/apache2/sites-available/your_domain.conf

##########################################
/etc/apache2/sites-available/your_domain.conf

<VirtualHost *:80>
        ServerAdmin your_email
        ServerName your_domain

</VirtualHost>

############################################


Install certificate using certbot
https://certbot.eff.org/

Now use the tools published by Fred and team to setup coturn server. I used the scripts


https://github.com/bigbluebutton/bbb-install#install-a-turn-server
and 
http://docs.bigbluebutton.org/2.2/setup-turn-server.html#configure-bigbluebutton-to-use-the-coturn-server

On the coturn server I edited from the script config file (/etc/turnserver.conf) to enable realm
realm=example.com



When done used the script
turnserver -L <public_ip_address> -a -f -r <realm-name>
from 
https://github.com/coturn/coturn/wiki/CoturnConfig

I like this one because it shows the log errors

I got the error to suggest other program listening on port 443

To find the program run
lsof -i :433

from
https://askubuntu.com/questions/278448/how-to-know-what-program-is-listening-on-a-given-port

Im my case Apache was running. I then stopped Apache using 
systemctl stop apache2.service

Then I ran 
turnserver -L <public_ip_address> -a -f -r <realm-name>

I connected to bigbluebutton server behind firewall and got sound etc 

I did not need to edit /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini to to get coturn server to work.

**Comment by capilkey** [comment]
The client uses turn-stun-servers.xml for both the audio and video WebRTC connections. The configuration under /etc/kurento is specifically for whether or not Kurento should be using a TURN server for its side of the call, but that should never be needed.

**Comment by capilkey** [comment]
Gonna close this as there's no issue with the actual product.

**Comment by KurJay** [comment]
> > Also can some one help with the variables in /etc/turnserver.conf.
> 
> Which variable are you looking for. Also, you can use `bbb-install.sh` to automate the setup of a coturn server, see
> 
> https://github.com/bigbluebutton/bbb-install#install-a-turn-server

hi @ffdixon how are you

I alredy install turn using this lin

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s bbb.example.com -e info@example.com -g -c turn.example.com:1234abcd

But how we check the status is on? cause I try to connect my iphone and still 1020 error 

Regards

**Comment by ffdixon** [comment]
See also

 http://docs.bigbluebutton.org/2.2/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6
