### ISSUE TITLE
bbb-webhooks cannot be installed

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7995]
In the latest 2.2-beta `bbb-webhooks` cannot be installed

```
~$ sudo apt-get -y install bbb-webhooks
Reading package lists... Done
Building dependency tree
Reading state information... Done
bbb-webhooks is already the newest version (1:2.2.0-12).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up bbb-webhooks (1:2.2.0-12) ...
Can't find a config template
dpkg: error processing package bbb-webhooks (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 bbb-webhooks
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by GhaziTriki** [comment]
Fixed in 2.2-beta22

**Comment by jvieille** [comment]
This issue is still on. This what is currently installed on my server:
[root@bbb ~]# bbb-conf --version

ii  bbb-apps                              1:2.2.0-35                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-67                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-35                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-32                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-33                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-139                                     amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                          1:2.2.0-47                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-79                                      amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-9                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-52                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-815                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-4                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-26                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-52                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-swftools                          1:0.9.2-2                                       amd64        The swftools files for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-106                                     amd64        BigBlueButton API
iF  bbb-webhooks                          1:2.2.0-12                                      amd64        BigBlueButton Webhooks
ii  bbb-webrtc-sfu                        1:2.2.0-81                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-4                                       amd64        Open source web conferencing platform (bbb)
