### ISSUE TITLE
Unable to screenshare with Firefox 74.0 using https://test.bigbluebutton.org

### ISSUE THREAD

**Issue by mcfilib** [bigbluebutton/bigbluebutton#8802]
i'm trying to get screensharing working reliably and not having much luck. i've tried visiting https://test.bigbluebutton.org and, after enabling allowing screen sharing with the relevant dialogue, in the console i get the following errors:

```
[12:44:45:0661] ERROR: clientLogger: WebRTC peer constructor for screenshare (presenter) failed due to The object can not be found here. https://test.bigbluebutton.org/html5client/compatibility/kurento-extension.js?v=837:465:19

[12:44:45:0663] ERROR: clientLogger: Screenshare presenter failed when trying to start due to NotFoundError https://test.bigbluebutton.org/html5client/ff674e169b89da17bfbcb3cf00b91c4e6aaec27f.js?meteor_js_resource=true:125:1134118

[12:44:45:0664] ERROR: clientLogger: Default error handler for screenshare https://test.bigbluebutton.org/html5client/ff674e169b89da17bfbcb3cf00b91c4e6aaec27f.js?meteor_js_resource=true:125:412571
```

I’ve tried starting firefox in safe mode to rule it out being a problem being with one of my extensions blocking something critical. i am not connecting using a vpn or behind a nat firewall (https://github.com/bigbluebutton/bigbluebutton/issues/7829, https://github.com/bigbluebutton/bigbluebutton/issues/8792). furthermore, screensharing with google chrome on https://test.bigbluebutton.org/ works perfectly fine.

**Comment by mcfilib** [comment]
![image](https://user-images.githubusercontent.com/802389/76918226-ef69ab00-6919-11ea-873d-734001a67758.png)

**Comment by prlanzarin** [comment]
Hey @mcfilib, can you try it again on test.bigbluebutton.org? We ran an update there, I wanna try to rule out a known issue that was fixed a while ago before we debug it any further.

**Comment by mcfilib** [comment]
hey @prlanzarin, thanks for chiming in. i gave this another go today and still have the same issue unfortunately.

**Comment by prlanzarin** [comment]
@mcfilib Thans for the info. Can you confirm the macOS version you're using, please?

**Comment by mcfilib** [comment]
sure thing. i'm using catalina on this machine.

**Comment by boychi** [comment]
same issue, FF 74 on linux (Ubuntu 18.04), mac catalina, windows 10

**Comment by mcfilib** [comment]
looks like you've been inundated with new issues since the pandemic (how dystopian that sounds).

i actually think this is an upstream issue in firefox itself because none of the screen capture apis work for me on firefox. 

@boychi if you have a minute, would you mind trying the example at the bottom of [this mozilla guide](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) and let me know if it returns an error for you?

**Comment by prlanzarin** [comment]
Yeah, sorry @mcfilib. I had it written down to get back to you but it flew right over me due to other stuff getting in the way.
I think it's a Firefox issue. I saved the following bugzilla links which indicate screen capture via getDisplayMedia might be broken in mac catalina. Some of them have OS level permission adjustment suggestions you might try out. I'm short of Mac/iOSs, so if you can test them and get back to us, that'd be good.

https://bugzilla.mozilla.org/show_bug.cgi?id=1606434
https://bugzilla.mozilla.org/show_bug.cgi?id=1612006
https://bugzilla.mozilla.org/show_bug.cgi?id=1606434#c1

**Comment by boychi** [comment]
@mcfilib  sorry for late reply. I tested screen capture on mozilla page as suggested and there was no  error (Linux, Mac, Windows - FF 74)
Then I tested again on test bbb server and on our server and everything worked.

**Comment by matiasilva** [comment]
Great to hear this has been solved. Closing now.
