### ISSUE TITLE
Audio is out of sync with the webcam video after recording

### ISSUE THREAD

**Issue by davidrojo** [bigbluebutton/bigbluebutton#8815]
**Describe the bug**
The audio is out of sync of the video webcam.

**To Reproduce**
Record a meeting with a webcam enabled with more of 30 minutes. Pausing and resuming the recording.

**Expected behavior**
The audio should be in sync with the video webcam

**Actual behavior**
As time goes on, the audio is getting more out of sync of the video, as longer the video is more out of sync it is. at the end of a video of 1 hour, the audio sounds like 10 seconds before the video.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 22

**Additional context**
If you need it I can provide the raw files to check an example.

**Comment by maikmerten** [comment]
I'm seeing the same problem with a local BigBlueButton instance. For long sessions, with recordings being paused and resumed, audio and video are very much out of sync. This is not a player/browser problem: The generated "webcams.webm" has audio and video out of sync, even when played back in a desktop media player.

**Comment by mailalaki** [comment]
same problem for me

**Comment by mailalaki** [comment]
@ffdixon

**Comment by TuxLeGrand** [comment]
Same problem for me, from a fresh new installation of BBB 2.2.0

OS client: Ubuntu 19.10
Browser: Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit)

To fix the issue temporarily for the recording, I have to change the value for 'audio_offset' in /usr/local/bigbluebutton/core/scripts/presentation.yml:
- For a video of 30 minutes (2 webcams):    audio_offset=2500
- For a video of 150 minutes (from 15 to 19 webcams):  audio_offset=8000

But it seems that the out of sync varies from the beginning to the end of the video (even after changing the value of audio_offset).

Does everyone have the same issues with BBB 2.2.0?

**Comment by TuxLeGrand** [comment]
I have forgotten to mention that BBB was running on a VM with 8 cores and 16 GB RAM (KVM on a dedicated server with Proxmox VE 6.1-8/Debian 10 with 8 cores / 32 GB RAM).

BBB was the only VM running during the meeting, to be sure that all host resources will be dedicated to the BBB VM (I was looking at system resources and none were reached: CPU/ram/net). 

For the meeting with 32 participants (with a max of 19 webcams displayed at test same time), the network bandwidth peak at 150 Mbps (on a 250 Mbps at OVH).

**Comment by thewebsitefactorylondon** [comment]
Hello guys
Thanks for starting this issue. I have the same problem with my install. There is a 15-20 seconds delay between audio and video when playing the recordings.
My server config:  (4 vCPUs / 8 GB Memory / 160 GB Disk / Ubuntu 16.04.6 (LTS) x64)
How to fix this?
Thanks

**Comment by davidrojo** [comment]
Hi I've been investigating, and I've found that the raw files of the recording are already out of sync, so it's not an issue in the publish process after the meeting.

I've opened in a video editor, the audio file (.opus) and the webcam video file of the raw folder of the recording, and after syncing them in the video editor, at the end they are out of sync. So the raw files are already out of sync.

As we have mentioned earlier the out of sync gets bigger and bigger as the recording advances, so the raw audio file generated has not the same "fps" than the video file generated.

@ffdixon

**Comment by thewebsitefactorylondon** [comment]
Hi @davidrojo 
Thank you for doing research on this. I'm still new to BBB and exploring its features and how it has been structured. It would be good if the recordings are synced.
Thanks

**Comment by JorritDeKlerk** [comment]
Same problem here. Downloaded the generated .webm files and resynced. Also the 30 minute mark seems to be the dealbreaker.

**Comment by thewebsitefactorylondon** [comment]
Any update on this issue? How to solve this? I'm running BBB 2.2.2 on DigitalOcean dedicated Droplet/Virtual Machine.

**Comment by davidrojo** [comment]
HI,

I've upgrated to latest version (2.2.16) and the problem persist.

I've investigated and it is only a webcam issue. When teachers record their desktop, the audio is correctly synced with it, also when they only use the whiteboard, the audio is correctly synced.

When teachers uses the webcam, the audio is out of sync with it, also if the teacher combines webcam and desktop sharing the audio is out of sync.

This is a big issue to the students as they cannot see the recordings correctly, and it is very dificult to study when what you are hearing is not what you are seeing.

**Comment by jibon57** [comment]
Yes, I am also having this problem. @basisbit did one pull here: https://github.com/bigbluebutton/bigbluebutton/pull/9597 but that didn't solve the recording problem.

**Comment by JorritDeKlerk** [comment]
Update on my side after using BBB two times a week recording 1,5 hour sessions. Combination of webcam, whiteboard and external Vimeo / Youtube. We have instructed our teachers to mute themselves when playing the Vimeo / Youtube. Currently, I download the finished recordings from the server and re-edit them inside an NLE. FIrst, to add the external Vimeo's/Youtube-movies (because they are not recorded by BBB) and second to resync, because all the recordings go out of sync.
The problem, I think, has to do with the periods of silence, because at that time the audio starts to go (way more) out of sync. So, I correct the sync, the presenter starts a Vimeo, the audio is muted, and when it's unmuted, the sync is worse.
Last week, I recorded a session, and I had to resync every time the presenter took a small pause when speaking.
So, something defintely goes wrong with the audio-recording (so, something to do with Freeswitch?)
If someone needs more info from the BBB-team, do not hesitate to ask. Next week we will evaluate BBB, because it now simply is too much time to manually edit the recordings.

**Comment by basisbit** [comment]
As workaround for the recording problems, you could use [Open Broadcaster Software](https://obsproject.com/) to record the session.

**Comment by davidrojo** [comment]
Hi, I just moved my BBB installation to a dedicated server and the audio is now correctly synced. So I think that the issue was because it was in a virtual server.

**Comment by mabras** [comment]
> dedicated server

Could you please elaborate on this. I mean what is specs, hosting? By dedicated, you mean metal?

Thanks.

**Comment by jibon57** [comment]
We are only using Dedicated bare metal for all of our BBBs & never used VPS (had plan but didn't). Still having this problem. So, problem should be something else.

**Comment by basisbit** [comment]
@jibon57 what are your ntpd settings - how do you do time synchronization on your dedicated servers? For some people, having ntpd only sync the clock during the middle of the night helped resolve the issue.

**Comment by jibon57** [comment]
@basisbit thanks for reply. I don't think I did any changes for that. It should be default as OS doing. Also I check your pull request & run multiple times to test but never saw any differences for time. But if you give suggestions then I can try.

**Comment by davidrojo** [comment]
@mabras Yes, I mean metal by dedicated ;)

I had a virtual server with the following specs:
8 vCPU
32 GB RAM
240 GB ssd

It was handling about 15 concurrent meetings with 160 attendees in total at peak hours. Some with webcams, others with sharing desktops and others with just the whiteboard. About 50 meetings per day with a total of about 400 attendees.

Live sessions were correct, but the recorded files were corrupted with audio outsync, the recorded raw files were already corrupted.

Now I have a dedicated server with the following specs:
- Intel® Core™ i7-6700 Quad-Core Skylake 
- 64 GB DDR4 
- 2x512 NVMe SSD (RAID 1)

Everything perfect, the recorded webcam is synced correctly with audio.

I have to say that I haven't done any special, just bbb-install script and configure some custom texts in bbb configuration files.

**Comment by jibon57** [comment]
@davidrojo I think you are using server from `hetzner` & I have same 2 servesr for my 2 BBBs but still having problem.

**Comment by davidrojo** [comment]
> @davidrojo I think you are using server from `hetzner` & I have same 2 servesr for my 2 BBBs but still having problem.

Yes, I am using hetzner servers. Are you having issues with virtual or dedicated?

**Comment by jibon57** [comment]
```
    Intel® Core™ i7-6700 Quad-Core Skylake
    64 GB DDR4
    2x512 NVMe SSD (RAID 1)
```

Same one

**Comment by davidrojo** [comment]
> ```
>     Intel® Core™ i7-6700 Quad-Core Skylake
>     64 GB DDR4
>     2x512 NVMe SSD (RAID 1)
> ```
> 
> Same one

I will wait for the rest of the day to see how the recordings are being processed, as I have installed the new server today, but the first class has been synced successfully.

**Comment by giameghub** [comment]
Hi I have the same problem with versione 2.1.0
I read the issue (closed)
https://github.com/bigbluebutton/bigbluebutton/issues/2268
When checked audio and video fps, I had 30 fps for video and 29.7 for audio. I think this causes the problem. Is there a way ti set both audio and video perhaps to lower values like 24 ?

**Comment by peterpetrov** [comment]
Hey Guys. I had that problem as well. My setup is virtual servers with dedicated CPU in Hetzner with 8 cores and 32 GB RAM. My issue was solved with upgrading to 2.2.15. The recordings are now synced properly on my end. However that does not help older recordings. The old recordings even rebuild will not sync.

I ope this helps.

**Comment by matiasilva** [comment]
Can anyone else report that this issue has been solved upon upgrading to the latest (2.2.17) version of BBB?

**Comment by mobcer** [comment]
I had 4 concurrent conferences yesterday with average of 10 attendance. I was checking my recordings today and i realized that recordings without having webcam on are just fine. The one with any webcam at any point of recording are hugely out of synce at the end of the file.

My setup is bbb server with 4 vcpu and 8gb ram running on a cloud.

**Comment by megamind89** [comment]
The issue still exists on a clean setup of BBB v2.2.19 for me. This happens not only with webcams recordings but also on ones where there's no webcams recording as well. The audio seems to be completely out of sync during playback. I tried setting the audio offset of a few seconds in the presentation.yml. This solves the issue initially but midway through the issue becomes prominent again. I have used the same config for the server as some of others have used above. Any updates would be appreciated.

**Comment by basisbit** [comment]
@megamind89 this is most likely a time synchronization problem on your server virtualization setup.

**Comment by megamind89** [comment]
@basisbit Thank you for the reply, so if I correct the ntp configuration on my server and rebuild old recordings would it work out? Or would it work only for future recordings?

**Comment by basisbit** [comment]
only for future recordings of course - the timing data is already written to disk. Especially when using anything VMWare, expect audio/video to go out of sync. Amazon EC2, Google Cloud and many low-latency & high performance KVM setups with dedicated physical CPU cores don't have those problems. You could try if disabling NTPD on the host and the VM, and then only syncing time during early morning, helps for your use case.

**Comment by megamind89** [comment]
Thank you for the information @basisbit . Yes, the NTP configuration was the culprit. Recordings now are recorded and even playback on sync. Safe to say doesn't happen anymore to me. I, also upgraded to 2.2.20.

**Comment by mailalaki** [comment]
hi, records of my dedicated server with the following specs is out of sync:
```
2X - Intel Xeon E5-2650 v2 @ 2.60GHz (16 core)
32GB Ram
6X - 900GB SAS 10K (raid 5)
```

I have another server with half the capacity of these resources, but I do not have a problem with that one, but I have a problem with this server. why?
If the problem is with NTP configuration, please help me. How should I configure it? thanks

**Comment by mailalaki** [comment]
> 
> 
> hi, records of my dedicated server with the following specs is out of sync:
> 
> ```
> 2X - Intel Xeon E5-2650 v2 @ 2.60GHz (16 core)
> 32GB Ram
> 6X - 900GB SAS 10K (raid 5)
> ```
> 
> I have another server with half the capacity of these resources, but I do not have a problem with that one, but I have a problem with this server. why?
> If the problem is with NTP configuration, please help me. How should I configure it? thanks
> @basisbit

Can anyone help?
@matiasilva @basisbit @ffdixon @megamind89

**Comment by basisbit** [comment]
@mailalaki what virtual machine software do you use, or is your BigBlueButton directly installed on that hardware?

**Comment by mailalaki** [comment]
Hi @basisbit, Thanks for the reply. No virtualization is performed on the server and it is installed directly on the hardware.

**Comment by mailalaki** [comment]
> Hi @basisbit, Thanks for the reply. No virtualization is performed on the server and it is installed directly on the hardware.

on fresh install of latest BBB v2.2.21 with bbb-install.sh

**Comment by basisbit** [comment]
in that case there should be no audio-/video-sync problems except for the maybe 200ms of audio buffer if packet-loss/jitter is detected by the client.

**Comment by mailalaki** [comment]
So what could be the cause? Is there anything we need to do?
Our problem is the incremental out-of-sync when using a webcam in a meeting... Exactly like this https://github.com/bigbluebutton/bigbluebutton/issues/8815#issue-584497711

**Comment by alialic** [comment]
> @basisbit thanks for reply. I don't think I did any changes for that. It should be default as OS doing. Also I check your pull request & run multiple times to test but never saw any differences for time. But if you give suggestions then I can try.

hi, if solve problem? This is exactly the problem I am facing.

**Comment by sparse91** [comment]
Same problem with bbb 2.2.25. bbb is on vm. Is there any workaround?

**Comment by Martin-XIMR** [comment]
This problem is becoming pain in the neck.

The audio video go out of sync only when webcam or screen sharing is used.

I have a VM with Dedicated 24 core CPU  / 80 GB of Memory / SSD

@ffdixon Please find a solution.

**Comment by basisbit** [comment]
@Martin-XIMR this issue is already closed. Please use the forums for support requests.
The issues you described are quite common with VMware or HyperV virtualization. Usually you can greatly reduce the problem by fixing your ntpd / ntp time synchonization service of the vm host and the vm itself to only update / sync the time during off-business hours for example in the night.

**Comment by Martin-XIMR** [comment]
> @Martin-XIMR this issue is already closed. Please use the forums for support requests.
> The issues you described are quite common with VMware or HyperV virtualization. Usually you can greatly reduce the problem by fixing your ntpd / ntp time synchonization service of the vm host and the vm itself to only update / sync the time during off-business hours for example in the night.

I have already set ntpd / ntp time synchronization service of the vm host and the vm OFF. But still the problem continues. 

Anyways Thank for your Reply @basisbit , I will use the forms.

Any Idea when can we expect the bbb 2.3 to release

**Comment by ffdixon** [comment]
> Any Idea when can we expect the bbb 2.3 to release

We're working on it -- you can expect to see another release of 2.3-alpha in a few weeks.

**Comment by LMSSPACE** [comment]
Hello to everybody.
the issue is still continuing and really it's annoying our students. 
can anyone find a solution ???

I'm using the latest release 2.2.28

**Comment by basisbit** [comment]
@LMSSPACE For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

This issue here is already closed because the described problem in the software is fixed. If you still experience problems, thats very likely related to your local setup / configuration.

**Comment by mikhailnov** [comment]
Could you please explain why virtualization and/or server load may cause missync?

**Comment by mikhailnov** [comment]
Hm, did anyone compare e.g. systemd-timesyncd and e.g. chronyd and influence of difference in their algorithms on the missync of recordings?
