### ISSUE TITLE
BBB does not start properly after reboot OS (Only bbb-conf --restart works well)

### ISSUE THREAD

**Issue by MrCapitalist** [bigbluebutton/bigbluebutton#9182]
Hi
Thank a lot for creating this powerfull platform
I installed BBB using step by step instruction in [installation page](http://docs.bigbluebutton.org/2.2/install.html) on a fresh Ubuntu 16.04.06

Everythings installed well and I can login to rooms and use features (Except media share because I didn't run it on SSL address). But when I enter `sudo bbb-conf --status` in my console, it shows me these lines:

```
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✘ - failed]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✘ - failed]
bbb-web ———————————————► [✔ - active]
```

What is bbb-webrtc-sfu or etherpad and why they are in failed status?! I even completely restart my server but this problem has not been resolved.

My server is dedicated and it has 24 cores CPU with 40GB RAM and 400GB SSD

**Comment by runout-at** [comment]
did you try `bbb-conf --restart`?

**Comment by SasanGF** [comment]
> did you try `bbb-conf --restart`?

OMG!! Why I didn't try it before??! I entered it and all of them turn into "Active"!! I restarted whole of my OS before and didn't help me. Anyway, thanks a lot.

Have a good time

**Comment by runout-at** [comment]
ok. but maybe I'd consider this as a bug because I have a similar problem and I was just thinkong about opening an issue for that.

BBB should work after a reboot and it should not be necessary to run `bbb-conf --restart.

So please, can you reopen this issue again. thx!

**Comment by runout-at** [comment]
thanks for reopening.

maybe a renaming to something like  _BBB does not start properly after reboot_ would bee good.

**Comment by SasanGF** [comment]
Of course, I have to add that, after I created this topic and before you answer me, I opened [this page](https://github.com/bigbluebutton/etherpad-lite) and run these codes:

`curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt install -y nodejs
git clone --branch master https://github.com/ether/etherpad-lite.git && cd etherpad-lite && bin/run.sh`

And then I checked here and entered `bbb-conf --restart`

**Comment by basisbit** [comment]
@runout-at are you sure you got exactly the same issue? So `bbb-conf --status` shows everything fine except for sfu  and a reboot does not fix it but it works again after `bbb-conf --restart` until after next boot, then it is broken again?

**Comment by runout-at** [comment]
> @runout-at are you sure you got exactly the same issue? So `bbb-conf --status` shows everything fine except for sfu and a reboot does not fix it but it works again after `bbb-conf --restart` until after next boot, then it is broken again?

not for sure. right now it works after a reboot and I can't reproduce it. 2 days ago i had the problem but did not check the status before restarting manually (my bad). I did not perform any upgrades since then.

i think it's not a problem of the applications or their config because they will be active after a `bbb-conf --restart`

this could be a problem with systemd. i'v seen issues like this several times on other applications where the start of services after a reboot did not succeed. maybe a race condition, not starting services in a proper sequence,... normally if i did change to sysv the problems were gone. (I don't want to start a discussion about systemd vs sysv here! but it would be great if there would be a sysv start script too.)

**Comment by matiasilva** [comment]
As mentioned in the other issue, maybe have to do with not all of the BBB components starting in a predefined order. `sudo bbb-conf --restart` ensures this. Closing for now due to inactivity + problem has been solved.

**Comment by runout-at** [comment]
On Thu, 2020-06-18 at 05:57 -0700, Matias Silva wrote:
> As mentioned in the other issue, maybe has to do with not all of the
> BBB components starting in a predefined order. `sudo bbb-conf --
> restart` ensures this. Closing for now due to inactivity + problem
> has been solved.

As the other issue was closed recently too, i'd say this should stay
open until it is solved.
The problem is still here in the latest BBB-version.

**Comment by matiasilva** [comment]
If you're using Greenlight #8925 might help.

I'll reopen this then but I don't see why running `bbb-conf --restart` on restart doesn't work for you.

**Comment by runout-at** [comment]
On Thu, 2020-06-18 at 10:56 -0700, Matias Silva wrote:
> If you're using Greenlight #8925 might help.

It's not related to Greenlight. The same happens if the session is
opened via Moodle.

> I'll reopen this then but I don't see why running `bbb-conf --
> restart` on restart doesn't work for you.

The suggestion `bbb-conf --restart` came from me and it works. but this
is not a solution - the bug still exists.
After a reboot of the server bbb should start properly.

I tried to restart several services one by one but this does not work.

**Comment by ffdixon** [comment]
Just installed the latest build of BigBlueButton on a Digital Ocean c-8 server.  After multiple reboots, it comes up each time.

Are you able to reproduce the reboot issue on your server?  If so, what is your server's configuration?

**Comment by runout-at** [comment]
the original install was around 14th March 2020.

this problem occurred first time around mid April as far as i remember. and persists until now - latest version.

the output of _bbb-conf --check_ (obfuscated):

```
BigBlueButton Server 2.2.20 (2037)
                    Kernel version: 4.15.0-107-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 18387 MB
                         CPU cores: 12

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.example.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.example.com
                              port: 80, [YY:YY:YY:YY:YY::YY]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://HOST
                              red5: HOST
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: XXX.XXX.XXX.XXX
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.example.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: $freeswitch_addr

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: XXX.XXX.XXX.XXX
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: XXX.XXX.XXX.XXX
                    localIpAddress: XXX.XXX.XXX.XXX
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 968
                        kurentoUrl: wss://bbb.example.com/bbb-webrtc-sfu
                  enableListenOnly: true
```

**Comment by leobr2014** [comment]
I identified the problem on **bbb-web** after rebooting the OS on some VPS.

Maybe it's some problem in the order that each component is started.

**Comment by ffdixon** [comment]
It might be related to the startup sequence.  If after reboot you do a `sudo bbb-conf --restart` does it work again?

**Comment by leobr2014** [comment]
Hi Fred, 
I have solved this problem on my VPS by changing the boot sequence of the following bbb services with 
After=redis-server.service :

nano /lib/systemd/system/bbb-apps-akka.service
nano /lib/systemd/system/bbb-fsesl-akka.service
nano /lib/systemd/system/bbb-transcode-akka.service


[Unit]
Description=XXXXXXX
Requires=network.target
After=redis-server.service

And now it works fine

**Comment by leobr2014** [comment]
> 
> 
> It might be related to the startup sequence. If after reboot you do a `sudo bbb-conf --restart` does it work again?

Yes, work again.

**Comment by runout-at** [comment]
On Sun, 2020-08-02 at 17:06 -0700, leobr2014 wrote:
> I have solved this problem on my VPS by changing the boot sequence of
> the following bbb services with 
> After=redis-server.service :
> 
> nano /lib/systemd/system/bbb-apps-akka.service
> nano /lib/systemd/system/bbb-fsesl-akka.service
> nano /lib/systemd/system/bbb-transcode-akka.service

thanks a lot for figuring that out!
i can confirm this works for me too.

i just would recommend to edit the files through the /etc paths as this
should be the standard way for debian based systems:

/etc/systemd/system/multi-user.target.wants/bbb-apps-akka.service 
/etc/systemd/system/multi-user.target.wants/bbb-fsesl-akka.service 
/etc/systemd/system/multi-user.target.wants/bbb-transcode-akka.service 

markus

**Comment by ffdixon** [comment]
Thanks for figuring this out -- we'll see if we can incorporate this into the build.
